package uz.freelance.calculatorapp.models

enum class Expression {
    PLUS, MINUS, MULTIPLY, DIVIDE, PERCENTAGE, DOT, OPEN_PARENTHESIS, CLOSE_PARENTHESIS, SIN, COS, TAN, LN, LOG, DIV1_TO_X, E_IN_DEGREE_X, IN_DEGREE_X, PI, E, NUMBER, SQRT, DOUBLE, STRANGE_NUMBER_DOT, SQUARE,ABS
}